version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.0

# Filter for release tags.
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

workflows:
  test-deploy:
    jobs:
      - orb-tools/pack:
          filters:
            tags:
              only: /.*/
      - orb-tools/publish:
          name: publish-development-release
          orb_name: ankorstore/toolbelt
          vcs_type: << pipeline.project.type >>
          pub_type: dev
          requires:
            - orb-tools/pack
          context: orb-publishing
          filters:
            tags:
              ignore: /.*/
      - orb-tools/publish:
          name: publish-production-release
          orb_name: ankorstore/toolbelt
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
          context: orb-publishing
          filters: *release-filters
