version: 2.1
orbs:
  toolbelt: ankorstore/toolbelt@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  branches:
    ignore: master
  tags:
    only: /.*/

workflows:
  test-deploy:
    jobs:
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: ankorstore/toolbelt
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
