name: Check Semver Label
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
jobs:
  check-semver-label:
    name: Check Semver Label
    runs-on: ubuntu-latest
    steps:
      - id: check-semver-label
        uses: mheap/github-action-required-labels@v3
        with:
          mode: exactly
          count: 1
          labels: "patch, minor, major"
